services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    command: "server -dev"

  myweatherapi:
    build: ./MyWeatherApi
    depends_on:
      - vault
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "myroot"
    ports:
      - "5001:8080"

  myweatherapp:
    build: ./MyWeatherApp
    depends_on:
      - vault
      - myweatherapi
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "myroot"